services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=blooddb
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'blooddb:/var/lib/postgresql/data/'
  spring:
    image: bd
    build:
      context: git@github.com:alexioudim/BloodDonor.git#rest
      dockerfile: backend.Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blooddb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    image: bdvue
    build:
      context: git@github.com:TasosK7/BloodDonorVue.git
      dockerfile: Dockerfile
    environment:
      -VITE_BACKEND=http://4.211.108.10:7070
    ports:
      - 9000:80
    depends_on:
      spring:
        condition: service_healthy


volumes:
  blooddb: