apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
spec:
  rules:
    - host: bd-spring.ddns.net
      http:
        paths:
          - pathType: Prefix
            path: /app
            backend:
              service:
                name: spring
                port:
                  number: 7070
